#!/usr/bin/env node

/**
 * Converts the single-stroke SVG fonts from the `hersheytext` package into compact TypeScript
 * data (lib/text/font-data.ts) so the app never has to parse SVG at runtime.
 *
 * Run after changing FONTS below:  npm run build-fonts
 */

const fs = require('fs');
const path = require('path');

const FONTS = [
  { id: 'print', label: 'Print', file: 'EMSReadability.svg' },
  { id: 'handwriting', label: 'Handwriting', file: 'EMSFelix.svg' },
  { id: 'cursive', label: 'Cursive', file: 'HersheyScript1.svg' },
  { id: 'calligraphy', label: 'Calligraphy', file: 'EMSAllure.svg' },
];

const fontDir = path.join(path.dirname(require.resolve('hersheytext/package.json')), 'svg_fonts');
const outFile = path.join(__dirname, '..', 'lib', 'text', 'font-data.ts');

const decode = (s) =>
  s
    .replace(/&quot;/g, '"')
    .replace(/&apos;/g, "'")
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&#x([0-9a-f]+);/gi, (_, h) => String.fromCodePoint(parseInt(h, 16)))
    .replace(/&amp;/g, '&');

/** Highest / lowest y over the given glyphs' strokes. */
const extent = (glyphs, chars, pick) =>
  pick(...chars.flatMap((ch) => glyphs[ch][1].flatMap((st) => st.filter((_, i) => i % 2 === 1))));

const attr = (tag, name) => {
  const m = tag.match(new RegExp(`\\s${name}="([^"]*)"`));
  return m ? m[1] : undefined;
};

/** "M x y L x y ..." → [[x, y, x, y, ...], ...] (font units, y up, rounded to integers). */
function parsePath(d) {
  const strokes = [];
  let current = null;
  const tokens = d.match(/[ML]|-?\d*\.?\d+(?:e[-+]?\d+)?/gi) || [];
  let command = null;
  for (let i = 0; i < tokens.length; ) {
    if (/^[ML]$/i.test(tokens[i])) {
      command = tokens[i++].toUpperCase();
    } else if (command === 'M') {
      // Extra coordinate pairs after a move are implicit line-tos (SVG path grammar).
      command = 'L';
    } else if (command === null) {
      throw new Error(`Path data must start with a command: ${d.slice(0, 40)}`);
    }
    const x = Math.round(Number(tokens[i++]));
    const y = Math.round(Number(tokens[i++]));
    if (command === 'M' || !current) {
      current = [x, y];
      strokes.push(current);
    } else {
      current.push(x, y);
    }
  }
  return strokes;
}

const fonts = FONTS.map(({ id, label, file }) => {
  const svg = fs.readFileSync(path.join(fontDir, file), 'utf8');
  const metadata = (svg.match(/<metadata>([\s\S]*?)<\/metadata>/) || [])[1] || '';
  const face = svg.match(/<font-face[^>]*>/)[0];
  const glyphs = {};
  for (const [tag] of svg.matchAll(/<glyph\s[^>]*>/g)) {
    const unicode = attr(tag, 'unicode');
    if (unicode === undefined) continue;
    const char = decode(unicode);
    if ([...char].length !== 1) continue;
    glyphs[char] = [Math.round(Number(attr(tag, 'horiz-adv-x'))), parsePath(attr(tag, 'd') || '')];
  }
  return {
    id,
    label,
    source: metadata.match(/Font name:\s*(.+)/)[1].trim(),
    // The <font-face> header carries template values, so measure the real letters instead.
    metrics: {
      unitsPerEm: Number(attr(face, 'units-per-em')),
      ascent: extent(glyphs, ['H', 'l', 'd', 'f'], Math.max),
      descent: extent(glyphs, ['g', 'p', 'y', 'j'], Math.min),
      capHeight: extent(glyphs, ['H'], Math.max),
      xHeight: extent(glyphs, ['x'], Math.max),
    },
    glyphs,
  };
});

const banner = `// GENERATED by scripts/build-fonts.js from the \`hersheytext\` package. Do not edit.
// Font licences and acknowledgements: lib/text/FONTS-LICENSE.md
`;
const body = fonts
  .map((f) => `  ${JSON.stringify(f.id)}: ${JSON.stringify(f)},`)
  .join('\n');
fs.writeFileSync(
  outFile,
  `${banner}
import type { StrokeFont } from './types';

export const FONT_DATA = {
${body}
} satisfies Record<string, StrokeFont>;
`
);
console.log(
  `Wrote ${path.relative(process.cwd(), outFile)} (${(fs.statSync(outFile).size / 1024).toFixed(0)} KB): ` +
    fonts.map((f) => `${f.id}=${Object.keys(f.glyphs).length} glyphs`).join(', ')
);
