/**
 * Writes ready-made files for every catalog picture into /catalog:
 *   <id>.gcode  G-code for A4 portrait with the app's default plotter settings
 *   <id>.svg    the same strokes as an SVG preview
 * plus catalog/README.md listing them. The app generates G-code for the current Plotter
 * settings itself; these files are for sending to the robot directly.
 *
 * Run after changing lib/catalog/pictures.ts:  npm run export-catalog
 */

import { mkdirSync, writeFileSync } from 'fs';
import { join } from 'path';

import { CATALOG, pictureToSketch } from '../lib/catalog';
import {
  DEFAULT_PLOTTER_SETTINGS,
  penDownLine,
  penUpLine,
  planPlot,
  sketchToGcode,
  sketchToSvg,
} from '../lib/sketch/export';

const outDir = join(__dirname, '..', 'catalog');
mkdirSync(outDir, { recursive: true });

const settings = DEFAULT_PLOTTER_SETTINGS;
const rows: string[] = [];
for (const picture of CATALOG) {
  const sketch = pictureToSketch(picture);
  writeFileSync(join(outDir, `${picture.id}.gcode`), sketchToGcode(sketch, settings));
  writeFileSync(join(outDir, `${picture.id}.svg`), sketchToSvg(sketch));

  const plan = planPlot(sketch, settings);
  const xs = plan.strokes.flat().map((p) => p.x);
  const ys = plan.strokes.flat().map((p) => p.y);
  const size = `${Math.round(Math.max(...xs) - Math.min(...xs))}×${Math.round(Math.max(...ys) - Math.min(...ys))} mm`;
  rows.push(
    `| ![${picture.name}](${picture.id}.svg) | **${picture.name}** | ${picture.category} | ` +
      `${plan.strokeCount} | ${size} | ` +
      `≈ ${Math.max(1, Math.round(plan.minutes))} min | [${picture.id}.gcode](${picture.id}.gcode) |`
  );
}

writeFileSync(
  join(outDir, 'README.md'),
  `# Cartoon catalog

Ready-made G-code for the pictures in the app's **Draw → Catalog** tab. Generated by
\`npm run export-catalog\` from \`lib/catalog/pictures.ts\` — don't edit these files by hand.

These files use the app's default plotter settings: A4 portrait (${settings.paperWidthMm}×${settings.paperHeightMm} mm),
${settings.marginMm} mm margin, drawing at ${settings.drawFeedRate} mm/min, travel at ${settings.travelFeedRate} mm/min,
pen up \`${penUpLine(settings)}\`, pen down \`${penDownLine(settings)}\`, parking at the
nearest paper corner when done. If your robot is different,
export from the app instead — it uses your Plotter settings.

| Preview | Picture | Category | Strokes | Size | Time | G-code |
| --- | --- | --- | --- | --- | --- | --- |
${rows.join('\n')}
`
);
console.log(`Wrote ${CATALOG.length} pictures to ${outDir}`);
